import { type LucideProps, type LucideIcon } from 'lucide-react'
import {
  X,
  Plus,
  Menu,
  Search,
  PlusCircle,
  Bell,
  LayoutDashboard,
  Inbox,
  CreditCard,
  Wrench,
  Settings,
  HelpCircle,
  LoaderCircle,
  TrendingUp,
  Package,
  AlertTriangle,
  ShoppingBag,
  Calendar,
  Clock,
  CheckCircle,
  RotateCcw,
  Trash2,
  ChevronDown,
  ChevronUp,
  Receipt,
  Laptop,
  LogIn,
  Eye,
  EyeOff,
  ArrowLeft,
  List,
  ListOrdered,
  Tags,
  Pencil,
  ExternalLink,
  Check,
  ChevronLeft,
  ChevronRight,
  Home,
  User,
  Cpu,
  HardDrive,
  Zap,
  Code,
  GitBranch,
  Pentagon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  close: X,
  add: Plus,
  menu: Menu,
  search: Search,
  add_circle: PlusCircle,
  notifications: Bell,
  dashboard: LayoutDashboard,
  move_to_inbox: Inbox,
  payments: CreditCard,
  build: Wrench,
  build_circle: Wrench,
  settings: Settings,
  help: HelpCircle,
  progress_activity: LoaderCircle,
  trending_up: TrendingUp,
  inventory: Package,
  inventory_2: Package,
  warning: AlertTriangle,
  shopping_bag: ShoppingBag,
  today: Calendar,
  schedule: Clock,
  check_circle: CheckCircle,
  undo: RotateCcw,
  delete: Trash2,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  receipt_long: Receipt,
  laptop: Laptop,
  login: LogIn,
  visibility: Eye,
  visibility_off: EyeOff,
  arrow_back: ArrowLeft,
  list_alt: List,
  format_list_numbered: ListOrdered,
  sell: Tags,
  edit: Pencil,
  open_in_new: ExternalLink,
  check: Check,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  home: Home,
  person: User,
  memory: Cpu,
  storage: HardDrive,
  hard_drive: HardDrive,
  power: Zap,
  deployed_code: Code,
  pending: Clock,
  hub: GitBranch,
  pentagon: Pentagon,
}

interface IconProps extends Omit<LucideProps, 'name'> {
  name: string
}

export function Icon({ name, ...props }: IconProps) {
  const LucideIconComponent = iconMap[name]
  if (!LucideIconComponent) {
    console.warn(`Icon "${name}" not found`)
    return null
  }
  return <LucideIconComponent {...props} />
}
